substitutions:
  name: esphome-web-c89274
  friendly_name: Voicesensor Screen

  imagemodel1: "Luffy"
  imagewidth: "480"
  imageheight: "480"

  voiceear: "esphome_web_530014" #(voicear)
#  voiceear: "esphome_web_fa1d58" #respeaker lite

  # Voice assistant phases (must match the sending device)
  voice_assist_idle_phase_id: "1"
  voice_assist_waiting_for_command_phase_id: "2"
  voice_assist_listening_phase_id: "3"
  voice_assist_thinking_phase_id: "4"
  voice_assist_replying_phase_id: "5"
  voice_assist_not_ready_phase_id: "10"
  voice_assist_error_phase_id: "11"
  voice_assist_muted_phase_id: "12"
  voice_assist_playing_phase_id: "13"
  voice_assist_timer_finished_phase_id: "20"

  idle_illustration_file1: https://github.com/RealDeco/xiaozhi-esphome/raw/main/images/Other/${imagewidth}x${imageheight}/tron.png
  waiting_illustration_file1: https://github.com/RealDeco/xiaozhi-esphome/raw/main/images/${imagemodel1}/${imagewidth}x${imageheight}/idle.png
  listening_illustration_file1: https://github.com/RealDeco/xiaozhi-esphome/raw/main/images/${imagemodel1}/${imagewidth}x${imageheight}/listening.png
  thinking_illustration_file1: https://github.com/RealDeco/xiaozhi-esphome/raw/main/images/${imagemodel1}/${imagewidth}x${imageheight}/thinking.png
  replying_illustration_file1: https://github.com/RealDeco/xiaozhi-esphome/raw/main/images/${imagemodel1}/${imagewidth}x${imageheight}/replying.png
  loading_illustration_file1: https://github.com/RealDeco/xiaozhi-esphome/raw/main/images/${imagemodel1}/${imagewidth}x${imageheight}/loading.png
  error_illustration_file1: https://github.com/RealDeco/xiaozhi-esphome/raw/main/images/${imagemodel1}/${imagewidth}x${imageheight}/error.png
  timer_finished_illustration_file1: https://github.com/RealDeco/xiaozhi-esphome/raw/main/images/${imagemodel1}/${imagewidth}x${imageheight}/timer_finished.png
  mute_illustration_file1: https://github.com/RealDeco/xiaozhi-esphome/raw/main/images/${imagemodel1}/${imagewidth}x${imageheight}/mute.png
  playing_illustration_file1: https://github.com/RealDeco/xiaozhi-esphome/raw/main/images/${imagemodel1}/${imagewidth}x${imageheight}/playing.png

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2025.9.0
  name_add_mac_suffix: false
  on_boot:
    priority: 800
    then:
      - lvgl.widget.hide:
          id: request_box
      - lvgl.widget.hide:
          id: request_box_short
      - lvgl.widget.hide:
          id: response_box
      - lvgl.widget.hide:
          id: response_box_short

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"

psram:
  mode: octal
  speed: 80MHz

logger:

api:
  actions:
    - action: receive_stt_text
      variables:
        stt_text: string
      then:
        - if:
            condition:
              lambda: 'return stt_text.size() < 120;'
            then:
              - lvgl.widget.show:
                  id: request_box_short
              - lvgl.widget.hide:
                  id: request_box
              - lvgl.textarea.update:
                  id: request_box_short
                  text: !lambda 'return stt_text;'
            else:
              - lvgl.widget.show:
                  id: request_box
              - lvgl.widget.hide:
                  id: request_box_short
              - lvgl.textarea.update:
                  id: request_box
                  text: !lambda 'return stt_text;'

    - action: receive_tts_text
      variables:
        tts_text: string
      then:
        - if:
            condition:
              lambda: 'return tts_text.size() < 120;'
            then:
              - lvgl.widget.show:
                  id: response_box_short
              - lvgl.widget.hide:
                  id: response_box
              - lvgl.textarea.update:
                  id: response_box_short
                  text: !lambda 'return tts_text;'
            else:
              - lvgl.widget.show:
                  id: response_box
              - lvgl.widget.hide:
                  id: response_box_short
              - lvgl.textarea.update:
                  id: response_box
                  text: !lambda 'return tts_text;'

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

image:
  - file: ${idle_illustration_file1}
    id: casita_idle
    resize: ${imagewidth}x${imageheight}
    type: RGB565
  - file: ${waiting_illustration_file1}
    id: casita_waiting
    resize: ${imagewidth}x${imageheight}
    type: RGB565
  - file: ${listening_illustration_file1}
    id: casita_listening
    resize: ${imagewidth}x${imageheight}
    type: RGB565
  - file: ${thinking_illustration_file1}
    id: casita_thinking
    resize: ${imagewidth}x${imageheight}
    type: RGB565
  - file: ${replying_illustration_file1}
    id: casita_replying
    resize: ${imagewidth}x${imageheight}
    type: RGB565

  - file: ${error_illustration_file1}
    id: casita_error
    resize: ${imagewidth}x${imageheight}
    type: RGB565
  - file: ${timer_finished_illustration_file1}
    id: casita_timer_finished
    resize: ${imagewidth}x${imageheight}
    type: RGB565
  - file: ${loading_illustration_file1}
    id: casita_initializing
    resize: ${imagewidth}x${imageheight}
    type: RGB565
  - file: ${mute_illustration_file1}
    id: casita_muted
    resize: ${imagewidth}x${imageheight}
    type: RGB565
  - file: ${playing_illustration_file1}
    id: casita_playing
    resize: ${imagewidth}x${imageheight}
    type: RGB565

text_sensor:
  - platform: homeassistant
    id: ts_phase
    internal: true
#    entity_id: sensor.${voiceear}_voice_assistant_phase_id
    entity_id: input_text.phase_id_voiceear
    on_value:
      then:
        - logger.log:
            format: "Voice assistant phase: %s"
            args: [ "x.c_str()" ]

        # idle (1)
        - if:
            condition:
              lambda: 'return x == "${voice_assist_idle_phase_id}";'
            then:
              - lvgl.image.update:
                  id: assist_image
                  src: casita_idle
              - lvgl.widget.hide:
                  id: request_box
              - lvgl.widget.hide:
                  id: request_box_short
              - lvgl.widget.hide:
                  id: response_box
              - lvgl.widget.hide:
                  id: response_box_short

        # waiting for command (2)
        - if:
            condition:
              lambda: 'return x == "${voice_assist_waiting_for_command_phase_id}";'
            then:
              - lvgl.image.update:
                  id: assist_image
                  src: casita_waiting
              - lvgl.widget.hide:
                  id: request_box
              - lvgl.widget.hide:
                  id: request_box_short
              - lvgl.widget.hide:
                  id: response_box
              - lvgl.widget.hide:
                  id: response_box_short

        # listening (3)
        - if:
            condition:
              lambda: 'return x == "${voice_assist_listening_phase_id}";'
            then:
              - lvgl.image.update:
                  id: assist_image
                  src: casita_listening
              - lvgl.widget.hide:
                  id: request_box
              - lvgl.widget.hide:
                  id: request_box_short
              - lvgl.widget.hide:
                  id: response_box
              - lvgl.widget.hide:
                  id: response_box_short

        # thinking / processing (4)
        - if:
            condition:
              lambda: 'return x == "${voice_assist_thinking_phase_id}";'
            then:
              - lvgl.image.update:
                  id: assist_image
                  src: casita_thinking
              # Let receive_stt_text decide which request box to show.
              # Just ensure response boxes are hidden here.
              - lvgl.widget.hide:
                  id: response_box
              - lvgl.widget.hide:
                  id: response_box_short

        # replying (5)
        - if:
            condition:
              lambda: 'return x == "${voice_assist_replying_phase_id}";'
            then:
              - lvgl.image.update:
                  id: assist_image
                  src: casita_replying
              # Let receive_tts_text decide which response box to show.
              # Ensure request boxes are hidden here.
              - lvgl.widget.hide:
                  id: request_box
              - lvgl.widget.hide:
                  id: request_box_short

        # not ready / initializing (10)
        - if:
            condition:
              lambda: 'return x == "${voice_assist_not_ready_phase_id}";'
            then:
              - lvgl.image.update:
                  id: assist_image
                  src: casita_initializing
              - lvgl.widget.hide:
                  id: request_box
              - lvgl.widget.hide:
                  id: request_box_short
              - lvgl.widget.hide:
                  id: response_box
              - lvgl.widget.hide:
                  id: response_box_short

        # error (11)
        - if:
            condition:
              lambda: 'return x == "${voice_assist_error_phase_id}";'
            then:
              - lvgl.image.update:
                  id: assist_image
                  src: casita_error
              - lvgl.widget.hide:
                  id: request_box
              - lvgl.widget.hide:
                  id: request_box_short
              - lvgl.widget.hide:
                  id: response_box
              - lvgl.widget.hide:
                  id: response_box_short

        # muted (12)
        - if:
            condition:
              lambda: 'return x == "${voice_assist_muted_phase_id}";'
            then:
              - lvgl.image.update:
                  id: assist_image
                  src: casita_muted
              - lvgl.widget.hide:
                  id: request_box
              - lvgl.widget.hide:
                  id: request_box_short
              - lvgl.widget.hide:
                  id: response_box
              - lvgl.widget.hide:
                  id: response_box_short

        # playing (13)
        - if:
            condition:
              lambda: 'return x == "${voice_assist_playing_phase_id}";'
            then:
              - lvgl.image.update:
                  id: assist_image
                  src: casita_muted
              - lvgl.widget.hide:
                  id: request_box
              - lvgl.widget.hide:
                  id: request_box_short
              - lvgl.widget.hide:
                  id: response_box
              - lvgl.widget.hide:
                  id: response_box_short

        # timer finished (20)
        - if:
            condition:
              lambda: 'return x == "${voice_assist_timer_finished_phase_id}";'
            then:
              - lvgl.image.update:
                  id: assist_image
                  src: casita_timer_finished
              - lvgl.widget.hide:
                  id: request_box
              - lvgl.widget.hide:
                  id: request_box_short
              - lvgl.widget.hide:
                  id: response_box
              - lvgl.widget.hide:
                  id: response_box_short

switch:
  - platform: gpio
    name: Relay 1
    pin:
      number: GPIO40
      inverted: true
  - platform: gpio
    name: Relay 2
    pin:
      number: GPIO2
      inverted: true
  - platform: gpio
    name: Relay 3
    pin:
      number: GPIO1
      inverted: true

output:
  - platform: ledc
    id: backlight_output
    pin: GPIO38
    frequency: 150Hz
    min_power: 0.01
    zero_means_zero: true

light:
  - platform: monochromatic
    name: Backlight
    id: display_backlight
    output: backlight_output
    restore_mode: ALWAYS_ON
    default_transition_length: 1s

spi:
  - id: lcd_spi
    clk_pin: GPIO48
    mosi_pin: GPIO47

i2c:
  id: touchscreen_bus
  sda: GPIO19
  scl:
    number: 45
    ignore_strapping_warning: true

display:
  - platform: st7701s
    id: tft_display
    dimensions:
      width: 480
      height: 480
    # rotation: 270    #uncomment for placement with down-facing USB socket
    spi_mode: MODE3
    data_rate: 2MHz
    color_order: RGB
    invert_colors: False
    cs_pin: 39
    de_pin: 18
    hsync_pin: 16
    vsync_pin: 17
    pclk_pin: 21
    pclk_frequency: 12MHz
    pclk_inverted: False
    hsync_pulse_width: 8
    hsync_front_porch: 10
    hsync_back_porch: 20
    vsync_pulse_width: 8
    vsync_front_porch: 10
    vsync_back_porch: 10
    update_interval: never
    auto_clear_enabled: False
    init_sequence:
      - 1
      - [0xFF, 0x77, 0x01, 0x00, 0x00, 0x10] # CMD2_BKSEL_BK0
      - [0xCD, 0x00] # disable MDT flag
    data_pins:
      red: [11, 12, 13, 14, 0]
      green: [8, 20, 3, 46, 9, 10]
      blue: [4, 5, 6, 7, 15]

touchscreen:
  - platform: gt911
    id: tft_touch
    display: tft_display
#    transform:     #uncomment for placement with down-facing USB socket
#      swap_xy: true
#      mirror_x: true
    on_touch:
      then:
        - binary_sensor.template.publish:
            id: touch_input
            state: ON
    on_release:
      then:
        - binary_sensor.template.publish:
            id: touch_input
            state: OFF
        - homeassistant.action:
            action: button.press
            data:
              entity_id: button.${voiceear}_virtual_touch

binary_sensor:
  - platform: template
    name: "Touch Button"
    id: touch_input

lvgl:
  disp_bg_color: black
  widgets:
    - image:
        id: assist_image
        align: CENTER
        src: casita_idle   # default on boot

    - textarea:
        id: request_box_short
        text: ""
        align: BOTTOM_MID
        width: 440
        height: 80
        one_line: false

    - textarea:
        id: request_box
        text: ""
        align: BOTTOM_MID
        width: 440
        height: 140
        one_line: false

    - textarea:
        id: response_box_short
        text: ""
        align: BOTTOM_MID
        width: 440
        height: 80
        one_line: false

    - textarea:
        id: response_box
        text: ""
        align: BOTTOM_MID
        width: 440
        height: 140
        one_line: false
